version: '2'
services:
  Backdoor-Base:
    privileged: true
    image: mayankt/backdoor:dind
    stdin_open: true
    volumes:
    - /ssh-data:/data:rw
    - /Users/Mayank/.kube/config:/kube/config:ro
    dns:
    - 172.16.10.2
    tty: true
    labels:
      io.rancher.container.pull_image: always
      purpose: backdoor-base-image
  Backdoor-Proxy:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 222:222/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: host_type=infra
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
